defaults:
  - base_rl_config
  - _self_

device: auto
project_dir: ./projects/output/rl/predictive_traffic_rule_compliance
scenario_dir: /home/yanliang/commonroad-data/highd-dataset-converted
seed: 0
warmstart: False
profile: False

training:
  wandb_logging: True
  checkpoint_freq: 50000
  eval_freq: 10
  gradient_save_freq: 1
  log_freq: 1
  n_envs: 1
  n_eval_episodes: 10
  normalize_observations: False
  normalize_rewards: False
  normalize_rewards_threshold: 10.0
  record_backoff: 1.0
  video_frequency: 10000
  total_timesteps: 1_000_000 # original 1_000_000
  verbose: 0
  video_length: 1000

model:
  gae_lambda: 0.8
  gamma: 0.99
  n_epochs: 8
  ent_coef: 1e-2
  n_steps: 256
  batch_size: 32
  vf_coef: 0.5
  max_grad_norm: 10.0
  learning_rate: 5e-4
  clip_range: 0.2
  gnn_out_dim: 80
  gnn_hidden_dim: 80
  gnn_layers: 3

experiment:
  data_padding_size: 200
  edge_drawer_class_name: "KNearestEdgeDrawer"  # or "VoronoiEdgeDrawer"  
  dist_threshold_v2v: 50.0
  edge_drawer_k: 3
  ego_map_radius: 50.0
  
  render_on_step: False
  render_debug_overlays: True
  enable_traffic: True
  raise_exceptions: False

  linear_lanelet_projection: True
  enable_waypoint_resampling: True
  lanelet_waypoint_density: 10

  spawning:
    min_goal_distance: 100.0
    max_goal_distance: 150.0
    min_vehicle_distance: 10.0

  enable_sumo: True
  sumo_simulation:
    delta_time: &delta_time 0.2
    presimulation_steps: auto
    p_wants_lane_change: 1.0 # original 0.8
    p_spawn: 0.02

reactive_planner:
  planning:
    dt: 0.1
    replanning_frequency: 3
    time_steps_computation: 20

  vehicle:
    # CR vehicle type (see commonroad-vehicle-models): #1: Ford Escort, #2: BMW 320i, 3 = VW Vanagon
    id_type_vehicle: 2

  debug:
    show_plots: False
    save_plots: False
    draw_traj_set: False
    draw_icons: True
    multiproc: True
    num_workers: 6

  sampling:
    t_min: 0.2

cmd: "train"
